### ISSUE TITLE
Installed, but not available as a Caching option within FPC dropdown?

### ISSUE THREAD

**Issue by toobulo** [litespeedtech/magento2-LiteSpeed_LiteMage#1]
Hi there,

Following instructions exactly from here:  https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:litemage2:installation

We've installed this on a fresh Magento 2.0.7. It appears that there are no issues during install, however we do not get the option to select LiteMage from the Full Page Cache "caching application" dropdown (Stores > Configuration > Advanced > System > Full Page Cache) as seen here:

http://blog.litespeedtech.com/2016/04/08/litemage-2-for-magento-2-released-litemage-goes-open-source/

The extension is enabled, and even shows settings to enable loggging.  

![pasted_image_6_7_16__1_14_pm](https://cloud.githubusercontent.com/assets/3487773/15873245/902c2f5c-2cb2-11e6-9613-f169514e2293.jpg)

**Comment by rkhoury82** [comment]
Did you enable via .htaccess ? 

<IfModule LiteSpeed>
LiteMage on
</IfModule>

**Comment by ls-rob** [comment]
Hello toobulo,

Are you using a trial license? Regardless, please confirm that your LiteSpeed license has LiteMage cache enabled. If LiteMage is enabled in your license and it is still not showing up as an option in the drop down or if you are uncertain, you can send us your server ip and we can confirm on our end.

Regards,
~Rob

**Comment by toobulo** [comment]
Hey guys,

.htaccess was already set, and it was not a trial license.  However, it's since been fixed and apparently was the server configuration itself, as per our server admin:

> To fix this, I tried force upgrading LiteSpeed with its latest build.

Thanks for the quick response!

**Comment by ewallkrishnaprakash** [comment]
Hi Guys,

We are also finding the issue in FPC drop down. The "LiteMage" option not showing in the drop down. We have enterprises litespeed web server and we have the enable the litespeed on our .htaccess file. Still the option is not showing.

**Comment by litespeedtech** [comment]
LiteMage module is not included by default in enterprise license. Only the trial license has LiteMage module enabled. 

If you want to verify whether your license has LiteMage module enabled, you can:
1. from cPanel WHM LiteSpeed plugin, check license info;
2. from LiteSpeed WebServer WebAdmin panel - Version Management - License Info;
3. email sales@litespeedtech.com with your serial number.

If you are on a shared hosting server and do not have above info, you can ask your host to check using above methods.
