### ISSUE TITLE
  Circular dependency Error

### ISSUE THREAD

**Issue by photolink** [litespeedtech/magento2-LiteSpeed_LiteMage#10]
We have recently had the LiteMage extension installed by our hosting company however the following error is showing:

Circular dependency: Litespeed\Litemage\Model\CacheControl depends on Litespeed\Litemage\Observer\FlushCacheByTags and vice versa.

Has anyone seen this or have a fix for it?

Steps taken:
- Extension installed
- Extension Enabled
- Setup:Upgrade run
- Static files deployed

**Comment by litespeedtech** [comment]
Is this happened when you try to upgrade your theme? Or just try to enable LiteMage extension?

**Comment by photolink** [comment]
We have only tested it by taking all the steps mentioned above. The host (Simple Servers) did other checks and were not able to get it working.

The site is on Magento CE 2.1.0.

**Comment by rkhoury82** [comment]
@photolink Did you re-compile ? 

Extension installed
Extension Enabled
Setup:Upgrade run
setup:di:compile
setup:static-content:deploy
cache:clean

**Comment by photolink** [comment]
No we have not compiled the site as yet. After the upgrade process we just deployed the static content.

**Comment by rkhoury82** [comment]
If you are running in default or production mode you really need to run the compile command.
You can check by deploy:mode:show

**Comment by lingwooc** [comment]
@photolink I am using the same host with litemage without problems. That said their support guys are pretty limited in my experience until you get to third tier. I'm using magento 2.1.3 and litemage 2.0.4

Definitely try compiling as @rkhoury82 suggests. The dependency injection stuff gets set up then, which is what it is complaining about. Magento always tells me to compile after a setup:upgrade anyway.

**Comment by litespeedtech** [comment]
@photolink I put some new updates, have not labeled to release 2.0.5. Can you test it and confirm if the error goes away?

**Comment by litespeedtech** [comment]
I tagged release 2.0.5. I believe your issue should be fixed. Please confirm.

**Comment by photolink** [comment]
Thanks - the new version has worked to the extent that the site is running and i was able to select LiteMage as the FPC caching option; however, when checking the response header, i am not seeing the expected value.

**Comment by litespeedtech** [comment]
If you see the page is not cached, means that url is not cacheable. If you switch to built-in cache, it will also not cached. You need to find out from the layout file which block caused that. If you email to info@litespeedtech.com to request adding to slack team, I can help you trouble shoot there.

**Comment by photolink** [comment]
The issue is now sorted following the 2.0.5 update and removing some cache blocking code. Thanks Lauren for your assistance.
