### ISSUE TITLE
Cache invalidation on REST PUT/POST

### ISSUE THREAD

**Issue by lingwooc** [litespeedtech/magento2-LiteSpeed_LiteMage#12]
I think I'm right in saying that an alteration to a product through the admin panel would trigger a cache invalidation for just that product.

I make a lot of changes to my store using the default REST interface. Is the litemage cache invalidation linked to this? It seems to be at best a bit hit and miss.

**Comment by litespeedtech** [comment]
For cache invalidate, litemage2 should follow same behavior as their built-in cache. Sof if you switch to built-in cache, are you able to have them properly purged?
It's possible for litemage2 to add some programmatic  interface to let you purge extra stuff. I may add this feature in next release.

**Comment by litespeedtech** [comment]
In v2.2, added webapi_rest/di.xml and webapi_soap/di.xml to capture purge tags. Your issue should be resolved. You can also hook with event litemage_purge to add your own purge tags.
