### ISSUE TITLE
Error for Magento 2.2

### ISSUE THREAD

**Issue by ausl** [litespeedtech/magento2-LiteSpeed_LiteMage#13]
Hi,

Received following error on Magento 2.2, any ideas to resolve it?

PHP Fatal error: Uncaught TypeError: Argument 1 passed to Litespeed\Litemage\Model\System\Config\Source\ApplicationPlugin::afterToArray() must be an instance of Litespeed\Litemage\Model\System\Config\Source\Magento\PageCache\Model\System\Config\Source\Application, instance of Magento\PageCache\Model\System\Config\Source\Application\Interceptor given, called in /home/stautosc/public_html/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /home/stautosc/public_html/app/code/Litespeed/Litemage/Model/System/Config/Source/ApplicationPlugin.php:59

**Comment by darkspadez** [comment]
Where do you see this issue? How do you reproduce this issue? How did you install LiteMage?

**Comment by ausl** [comment]
Hi, this appears in my server's error_log, and basically i just installed it and it just happened. I didn't see anything from the website about this error so far.

I install followed the instruction here: https://ventraip.com.au/faq/article/using-litemage-cache-magento-2-x-store/

**Comment by ausl** [comment]
Everything seems work ok in the backend

**Comment by darkspadez** [comment]
As long as everything is working properly you can probably ignore this issue. We will take a look into fixing this issue so it does not log anymore.

**Comment by ausl** [comment]
Thx, I will report back if the issue is bigger than I described. Cheers

**Comment by litespeedtech** [comment]
Please test with v2.0.7, should be fixed. Please confirm and close.
