### ISSUE TITLE
How to bypass some url params like GCLID from adwords

### ISSUE THREAD

**Issue by tomekjordan** [litespeedtech/magento2-LiteSpeed_LiteMage#16]
HI. How to ignore some url params - like from google adwords GCLID param,
page content is the same, but they just GCLID param at the end of the url
How to avoid caching separately the same pages with different params?

Thanks for info - looking for solutionion for Litemage M1 and M2
Example how Amasty FPC does it in its config https://amasty.com/docs/lib/exe/fetch.php?media=full-page-cache-pages.png

T.

**Comment by jacksonlst** [comment]
You can try our new feature about "Drop query string" on 5.2.3
currently it is debug build and you can try the following command.
  /usr/local/lsws/admin/misc/lsup.sh -d -f -v 5.2.3 

It will be released very soon.

**Comment by litespeedtech** [comment]
this has been released. please test and confirm.

**Comment by tomekjordan** [comment]
HI. I see thats has been added, but configuration is totally unfriendly (htaacess)

It should be just in Litemage panel - just please add text area to input url params like:
utm
gclid
just like any other FPC extension does

**Comment by litespeedtech** [comment]
litemage cache is on the server side, does not go to PHP.  so even we add the config on litemage config, it will still need to update .htaccess for you. This can be added in future.

**Comment by tomekjordan** [comment]
Understood, but such text area with gclid, utm params
would be helpful for excluding crawler from trying to crawl such pages and bypass it from using with deep crawling list build

**Comment by litespeedtech** [comment]
if a robot is crawling this url, it will be served from cache or hit backend and save to cache without those params.
