### ISSUE TITLE
Magento Commerce (Enterprise) 2.2.x - compatibility with content schedule

### ISSUE THREAD

**Issue by tomekjordan** [litespeedtech/magento2-LiteSpeed_LiteMage#17]
HI. Is LiteMage compatiblie with Commerce version and 2.2.x content staging and schedules?
http://docs.magento.com/m2/ee/user_guide/cms/content-staging.html

This is especially needed for cms pages, banners/static blocks and catalog price rules

Thanks for info

**Comment by litespeedtech** [comment]
you can update to 2.0.8 and test other scenarios. I've compared with builtin cache, looks like that's the only event I'm missing.

**Comment by litespeedtech** [comment]
I'll close this issue since no further feedback.
