### ISSUE TITLE
Full Page Hits showing 0

### ISSUE THREAD

**Issue by Schoeny1** [litespeedtech/magento2-LiteSpeed_LiteMage#18]
Using LiteMage Standard on Magento 2.2.1

I can see that the response header that LiteMage is working. However the cache page in the admin shows 

Public Cache Hits  870
Full Page Hits  0
LiteMage Cached Objects  3099

Why would it be showing 0 for Full Page Hits?

**Comment by jacksonlst** [comment]
That's correct. Magento 2 doesn't count as full page, hence full page hits 0, you should look at Public Cache Hits 870 and LiteMage Cached Objects 3099. It means working well.
