### ISSUE TITLE
magento2 multi store having different domain for each store

### ISSUE THREAD

**Issue by sanjaykesari** [litespeedtech/magento2-LiteSpeed_LiteMage#19]
Hi, I'm running a magento2 website having 2 store and using different url(domain) for each store. I followed your given instruction to configure it but it's very strange, litespeed caching is hitting only for one url not for second. Please help me to sort out this issue.   

My website configuration:
Magento Version : 2.2.4
1 Website, 2 store
Store1 url : xyx.com(dummy)
Store2 url: abc.com(dummy)

Working for xyx.com but not for abc.com

I want to run litespeed caching for both store url. Please help me.

**Comment by litespeedtech** [comment]
You need to set up cache root folder pointing to same directory for both virtual hosts. You can create support tickets with us or go to our slack litemage2 channel if you still have troubles.
