### ISSUE TITLE
Magento 2.1 compatibility

### ISSUE THREAD

**Issue by navarr** [litespeedtech/magento2-LiteSpeed_LiteMage#2]
I'm running a version of Magento 2.1.2.  Your composer.json indicates that you require:
- magento/framework 100.1.0 < \* < 100.0.0
- magento/module-page-cache 100.1.0 < \* < 100.0.0

Magento 2.1.2 has:
- magento/framework:100.1.2
- magento/module-page-cache:100.1.1

Are there any plans to support these versions, or is this a "Pull Requests accepted" sort of deal?

**Comment by litespeedtech** [comment]
updated the version. all versions should be compatible. 
Let me know if you hit any issues.
