### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by mitkosaxa** [litespeedtech/magento2-LiteSpeed_LiteMage#22]
Hello,
After update to Magento 2.4 and try to run `php bin/magento setup:di:compile` command extension thrown following error:
 

> Deprecated Functionality: Array and string offset access syntax with curly braces is deprecated in /home/devwa
  pi/waa2.dev.wapi.bg/vendor/litespeed/module-litemage/Block/Backend/Cache/Management.php on line 89

**Comment by litespeedtech** [comment]
this has been fixed.
