### ISSUE TITLE
The Litemage option is not showing in our magento2.4.1 admin

### ISSUE THREAD

**Issue by rakeshdonga** [litespeedtech/magento2-LiteSpeed_LiteMage#23]
we have installed latest extension files: https://github.com/litespeedtech/magento2-LiteSpeed_LiteMage
and my magento version 2.4.1 and php version 7.3 but in backend option missing 

![Screenshot_4](https://user-images.githubusercontent.com/26105920/109626733-e55ead80-7b66-11eb-9139-7154b482937c.png)

please let me know what is the issue here?

**Comment by lucasRolff** [comment]
Have you done all the required steps in https://docs.litespeedtech.com/lscache/litemage/installation/#extension-installation ?

**Comment by rakeshdonga** [comment]
yes i will do it all steps

**Comment by gntlby** [comment]
Hello,
did you solve the problem?
I have same issue.

**Comment by spignataro** [comment]
I am experiencing this same issue. I have gone through the steps over and over and over. I have the latest version 2.1.8 within the latest version of Magento 2.4.3 Open Source. Now the issue occurred after moving from 2.4.2 to 2.4.3.

I have the direct download version as I wanted to have control over this not updating and so forth. 

I believe that this is a bug but I can't for the life of me figure out how to resolve it.

**Comment by spignataro** [comment]
I reinstalled the server and things began to show up again.
