### ISSUE TITLE
LiteMage Option under Caching Application not appearing

### ISSUE THREAD

**Issue by mihaikalif** [litespeedtech/magento2-LiteSpeed_LiteMage#26]
Hello guys,

Please support in having this verified. The option Litespeed option for Magento 2.4. under Caching Application not appearing even after I followed the proper installation: https://docs.litespeedtech.com/lscache/litemage/installation/

Please let me know if there is any issue with the configuration>>>
https://18.156.83.153/

**Comment by litespeedtech** [comment]
close this old issue. If you still have problem, please open a ticket or a new issue.
