### ISSUE TITLE
After new version (2.2) Magento 2.4.6 indexer issue

### ISSUE THREAD

**Issue by gntlby** [litespeedtech/magento2-LiteSpeed_LiteMage#32]
Hello,

I am having indexer:reindex problem after new version.

Warning: Undefined variable $source in /home/XXX/public_html/vendor/litespeed/module-litemage/Observer/FlushCacheByTags.php on line 71

Thanks for support.

<img width="1476" alt="lite" src="https://github.com/litespeedtech/magento2-LiteSpeed_LiteMage/assets/45899771/0c3ea4f1-f8ae-4c0a-b5a3-7821ae869bf7">

**Comment by litespeedtech** [comment]
Thanks, Will patch with v2.2.1, for now you can change "$source" to "CLI".
