### ISSUE TITLE
Error if magentos inventory management is disabled

### ISSUE THREAD

**Issue by philippeaellig** [litespeedtech/magento2-LiteSpeed_LiteMage#33]
We use a 3th pary Inventory Module and we disabled magentos inventory management. In this case, the Magento\InventorySalesApi\Api\GetProductSalableQtyInterface class is not available. You have to remove this class from the constructor and check if magentos Inventory System is enabled before you get this Interface:
`if ($moduleManager->isEnabled('Magento_Inventory'))`

https://github.com/litespeedtech/magento2-LiteSpeed_LiteMage/blob/870011a7ed073b30e9b2c60be532cdb771c8e87a/Observer/AfterOrderPlaced.php#L53

Error Message:
`Next ReflectionException: Impossible to process constructor argument Parameter #1 [ <required> Magento\InventorySalesApi\Api\GetProductSalableQtyInterface $salebleqty ] of Litespeed\Litemage\Observer\AfterOrderPlaced class in /var/www/webroot/ROOT/vendor/magento/framework/Code/Reader/ClassReader.php:57`

**Comment by litespeedtech** [comment]
Hi, Philip,
Thanks for your feedback, can you [join our slack](https://www.litespeedtech.com/slack), DM litespeed.lauren for further discussion?

**Comment by litespeedtech** [comment]
this should be fixed in v2.2.2 release.
