### ISSUE TITLE
Can't flush Magento Cache: Undefined array key "purge"

### ISSUE THREAD

**Issue by bst-biwac** [litespeedtech/magento2-LiteSpeed_LiteMage#36]
Description:
when flushing Magento cache via CLI, an error appears:
 Warning: Undefined array key "purge" in vendor/litespeed/module-litemage/Model/Config.php on line 332 

prerequisites
Magento Opensource 2.4.6-p2
Litemage 2.2.2

Steps to reproduce
1. bin/magento cache:flush

Expected result: Caches flushed
Actual result:  Warning: Undefined array key "purge" in vendor/litespeed/module-litemage/Model/Config.php on line 332

**Comment by litespeedtech** [comment]
This is caused by the newly add config options. You can go to the litemage settings page, save it first. This error should be gone. will update code to address this.

**Comment by litespeedtech** [comment]
https://github.com/litespeedtech/magento2-LiteSpeed_LiteMage/commit/20005efc2d8f7ab1678f898ee98c0077af8446d5 this should fix this error.
