### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by Eddcapone** [litespeedtech/magento2-LiteSpeed_LiteMage#38]
The documentation is missing. It gives 404:
https://docs.litespeedtech.com/lscache/litemage/overview/

**Comment by lslisa** [comment]
Please use this link: https://docs.litespeedtech.com/lscache/litemage/
Can you tell me where you saw the previous link to "overview" so that I can fix it?
Thanks, and apologies for any inconvenience!

**Comment by Eddcapone** [comment]
Sorry, can't find it anymore. It was a site I found in google.
