### ISSUE TITLE
No FPC hit

### ISSUE THREAD

**Issue by Eddcapone** [litespeedtech/magento2-LiteSpeed_LiteMage#39]
I am using [ClawRock Debug Extension](https://github.com/clawrock/magento2-debug). It shows I don't have a FPC hit, even after reloading the site mulltiple times.

![image](https://github.com/user-attachments/assets/682b05d1-17b3-47cd-8047-7ca173d43634)

I have a hit.litemage, why don't I get a hit for FPC?

![image](https://github.com/user-attachments/assets/b0b5aa6f-9ad0-4361-aa89-d4fb4a309d59)

All caches are enabled:

Current status:
                        config: 1
                        layout: 1
                    block_html: 1
                   collections: 1
                    reflection: 1
                        db_ddl: 1
               compiled_config: 1
                           eav: 1
         customer_notification: 1
                     full_page: 1
            config_integration: 1
        config_integration_api: 1
                   target_rule: 1
             config_webservice: 1
                     translate: 1

Tested on a fresh magento 2.4.4-p9 on production mode.

Is it because xdebug is installed?

**Comment by litespeedtech** [comment]
This is because ClawRock Debug Extension does not detect X-LiteSpeed-Cache hit. If you want it to show in their extension, you'll need to reach them to include LiteMage support. Or you need other tools to show the  X-LiteSpeed-Cache header value.
