### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by navarr** [litespeedtech/magento2-LiteSpeed_LiteMage#4]
Tagging your releases will allow them to show up in Packagist as that version, and will allow Composer to use semantic versioning to know which version of the module to install.

Tagged releases also show up in Packagist/Composer as "stable" - where as right now LiteSpeed_LiteMage could only be installed unstable.

The easiest way to do this is by [Drafting a New Release](https://github.com/litespeedtech/magento2-LiteSpeed_LiteMage/releases/new)

Typical version tags are like "v2.0.1" using the Semantic Versioning rules (Where Major is breaking (for whatever the declared API is), Minor is new, non-breaking features, and patch is bugfixes)

**Comment by litespeedtech** [comment]
Thank you, just added. and we'll properly tag it for all future releases.

**Comment by navarr** [comment]
Thank you!
