### ISSUE TITLE
Checkout not working

### ISSUE THREAD

**Issue by 6Ways** [litespeedtech/magento2-LiteSpeed_LiteMage#6]
When Lite Mage is activated in my Magento 2.1 installation, checkout no longer works. I have tried several .htaccess rules, but none seems to work. Does anyone have a suggestion for this problem?

**Comment by litespeedtech** [comment]
Are you using the default demo store or your own customized theme? any special checkout module used?

**Comment by 6Ways** [comment]
Thanks for your quick response. I use the Luma magento theme with only some css adjustments through a fallback theme. A number of self-written modules, but no checkout module (except a payment module).

When I want to checkout or cart, Magento indicates that the cart is empty. The mini cart works well.

**Comment by 6Ways** [comment]
Okay, I have now been working for how far I can test it. Maybe it has something to do with the mulistore environment? I also had problems with the Product Added to Cart Success Message, which came on every page view. Using the following lines in the .htaccess, it works now.

RewriteCond %{REQUEST_METHOD} ^HEAD|GET$
RewriteCond %{HTTP_COOKIE} !mage-cache-sessid
RewriteCond %{ORG_REQ_URI} !^/admin/
RewriteCond %{ORG_REQ_URI} !^/cart/
RewriteCond %{ORG_REQ_URI} !^/checkout/
RewriteRule .* - [E=Cache-Control:max-age=300]
