### ISSUE TITLE
Can find Option in dropdown "LiteMage Cache in LiteSpeed Web Server" in magento

### ISSUE THREAD

**Issue by pareshe** [litespeedtech/magento2-LiteSpeed_LiteMage#7]
We not have option "LiteMage Cache in LiteSpeed Web Server" 
http://www.awesomescreenshot.com/05867bcx93

That is because of there is not found $_SERVER['X-LITEMAGE'] ?

Thanks.

**Comment by pareshe** [comment]
Also we got error in /var/log/apache2/error_log

like:[public_html/beta/.htaccess:2] LiteMage feature is not licensed.

**Comment by litespeedtech** [comment]
Yes, if you don't see that option, can be caused by 2 reasons:
1. your LiteSpeed license needs to have LiteMage module enabled. Trial license contains LiteMage unlimited.
2. your magento installation .htaccess does not have "LiteMage on".

**Comment by pareshe** [comment]
1) My license is not trial , so how to include LiteMage in my license.
2) My .htaccess already have  "LiteMage on".

**Comment by sureshp007** [comment]
I got the same issue . I am using magento 2.1.1 , On admin configuration there is no option available like "LiteMage Cache in LiteSpeed Web Server" . My .htaccess have "LiteMage on" , And site is in developer mode . How can i solve this issue . 

Thanx

**Comment by jacksonlst** [comment]
You will need to check if your license includes LiteMage module or not by logging into your client area, select services -> your license -> configurable options. If not there, you should add it your license.
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:licenses:add-lscache
