### ISSUE TITLE
bin/magento cache:flush does not flush LiteSpeed's FPC

### ISSUE THREAD

**Issue by navarr** [litespeedtech/magento2-LiteSpeed_LiteMage#8]
Related to #5 

Now that the command no longer throws an error, the typical cache:flush command does not purge the cache on the LiteSpeed server, as one might expect it to - necessitating a "flush cache" from the admin panel.

**Comment by litespeedtech** [comment]
I cannot reproduce it in version 2.0.3. If you are in developer mode and turn on debug, do you see "Set purge header *  " logged in debug.log? 
works for me for both commands : 
bin/magento cache:flush full_page 
bin/magento cache:flush 

Lauren

**Comment by navarr** [comment]
Watching the log it looks like it's trying to and failing.  (Can't find the purge URL).

I'll need to talk to my hosting provider then.  Thanks!
